// src/components/organisms/CareerSection/index.tsx
"use client";

import DateLabel from "@/components/atoms/DateLabel";
import { useCareerTableSections } from "@/composables/useCareerTableSections";
import CareerSectionDocumentBody from "@/components/organisms/CareerSection/DocumentBody";
import CareerSectionProjectsGroupsBody from "@/components/organisms/CareerSection/ProjectsGroupsBody";
import { useCareerTableSectionState } from "@/composables/useCareerTableSectionState";

export default function CareerSection() {

  const { loadedCareerTableSections, updatedAt } = useCareerTableSectionState();
  const { isSecrets } =
    useCareerTableSections();

  return <>
    <section className="relative mb-5">
      <div className="text-5xl text-center">職務経歴書</div>
      <div v-if="isSecrets" className="text-xl">機密要素あり</div>
      <div className="absolute right-0 bottom-0 text-sm">
        {updatedAt && <DateLabel value={updatedAt} />} 更新
      </div>
    </section>
    <section className={`career-section border-2 ${isSecrets ? 'secret' : ''}`}>
      { loadedCareerTableSections.length &&
        loadedCareerTableSections.map((section, index) =>
           <>
             {
               section.type === 'document' && <CareerSectionDocumentBody
                 key={index}
                 label={section.label}
                 markdownText={section.detail}
               />
             }
             {
               section.type === 'project-groups' && <CareerSectionProjectsGroupsBody
                 key={index}
                 groups={section.groups}
               />
             }
           </>
         )
      }
    </section>
    {
      !loadedCareerTableSections.length &&
      <div className="mt-8 text-3xl text-center">
        「biographyData.jsonファイル選択」からファイルを選択してください
      </div>
    }
  </>
}

// src/components/organisms/CareerSection/index.vue
<script setup lang="ts">
import DateLabel from "~/components/atoms/DateLabel";
import { useCareerTableSections } from "~/composables/useCareerTableSections.ts";

const { loadedCareerTableSections, updatedAt, isSecrets } =
  useCareerTableSections();
</script>

<template>
  <section class="relative mb-5">
    <div class="text-5xl text-center">職務経歴書</div>
    <div v-if="isSecrets" class="text-xl">機密要素あり</div>
    <div class="absolute right-0 bottom-0 text-sm">
      <DateLabel v-if="updatedAt" :value="updatedAt" /> 更新
    </div>
  </section>
  <section
    v-if="loadedCareerTableSections.length"
    :class="`career-section border-2 ${isSecrets ? 'secret' : ''}`"
  >
    <template v-for="(section, index) in loadedCareerTableSections">
      <CareerSectionDocumentBody
        v-if="section.type === 'document'"
        :key="index"
        :markdown-text="section.detail"
        :label="section.label"
      />
      <CareerSectionProjectsGroupsBody
        v-if="section.type === 'project-groups'"
        :key="index"
        :groups="section.groups"
      />
    </template>
  </section>
  <section v-else>
    <div class="mt-8 text-3xl text-center">
      「biographyData.jsonファイル選択」からファイルを選択してください
    </div>
  </section>
</template>
