// src/components/atoms/EnvironmentLabel.vue
<script setup lang="ts">
type EnvironmentElement = string | [string, { version?: number | string }?];

const props = defineProps<{
  element: EnvironmentElement;
}>();

const elementName = computed(() => {
  return typeof props.element === "string" ? props.element : props.element[0];
});

const elementOptions = computed(() => {
  return typeof props.element === "string" ? undefined : props.element[1];
});
</script>

<template>
  <div class="inline-block">
    <span>{{ elementName }}</span>
    <template v-if="elementOptions">
      <i v-if="elementOptions.version"> (v{{ elementOptions.version }}) </i>
    </template>
  </div>
</template>

// src/components/atoms/EnvironmentLabel.tsx
"use client";

import { useMemo } from "react";

type EnvironmentElement = string | [string, { version?: number | string }?];

export default function EnvironmentLabel({
  element,
}: {
  element: EnvironmentElement;
}) {
  const elementName = useMemo(() => {
    return typeof element === "string" ? element : element[0];
  }, [element]);

  const elementOptions = useMemo(() => {
    return typeof element === "string" ? undefined : element[1];
  }, [element]);

  return (
    <div className={"inline-block"}>
      <span>{elementName}</span>
      {elementOptions?.version && (
        <i v-if="elementOptions.version"> {elementOptions.version} </i>
      )}
    </div>
  );
}
