// src/components/atoms/TeamNumberLabel.vue
<script setup lang="ts">
const props = defineProps<{
  value: number | [number, number];
}>();

const teamNumberStr = computed(() =>
  Array.isArray(props.value)
    ? `${props.value[0]}~${props.value[1]}`
    : `${props.value}`,
);
</script>

<template>
  <span>{{ teamNumberStr }}人</span>
</template>

// src/components/atoms/TeamNumberLabel.tsx
"use client";

import { useMemo } from "react";

export default function TeamNumberLabel({
  value,
}: {
  value: number | [number, number];
}) {
  const teamNumberStr = useMemo(
    () => (Array.isArray(value) ? `${value[0]}~${value[1]}` : `${value}`),
    [value],
  );

  return <span>{teamNumberStr}人</span>;
}
